#!/bin/bash
# This script is to be launched from TinNS src directory
#
if [[ $# -ne 3 ]]; then
	echo
	echo "Error - usage:" `basename $0` "<dest base path> <svnrevision.h file> <bin dir>" >&2
	exit 1
fi

if [[ ! -d $1 ]]; then
	echo
	echo "Destination directory $1 doesn't exist !"
	exit 2
fi

if [[ -f options.local ]]; then
	echo
	echo "WARNING: Local option file 'options.local' is present. Compiled binaries might be unsuitable for distribution depending on the options you put in this file."
	grep -v '#' options.local |grep DO_DEBUG > /dev/null
	if [[ $? -eq 0 ]]; then
	echo
		echo "Debug Symbols Generation is activated !!! Binaries will be HUGE !"
	fi
	echo
	echo -e "\tContinue with archive building ? (y/N)"
	read -s -n 1 answer
	if [[ "$answer" != "y" ]]; then
		exit 3
	fi
fi

if [[ ! -d ../.svn ]]; then
	current=`grep TINNS_SVN_REVISION $2 | sed 's/^.*"\([0-9]\+\)".*$/\1/'`
else
	v=`svnversion ..`
	current=`echo $v | sed 's/^\([0-9]*:\)\?\([0-9]\+[^0-9]*\)/\2/'`
fi

destfile=$1/tinns_v2.r${current}_bin.tar.bz2

cd ..
tar -cj --exclude .svn -f $destfile -T - <<ENDOFLIST
./LICENSE.txt
./CHANGELOG
./docs
./database
`find ./conf -name "*.conf" -type f`
$3/gameserver
$3/infoserver
$3/patchserver
ENDOFLIST

echo
if [[ $? -eq 0 ]]; then
	echo "Source archive built:"
else
	echo "An error occured ! Could not build source archive :"
fi
echo $destfile

